version: "3.8"

services:
  postgres:
    image: timescale/timescaledb-ha:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5433:5432"  # Changed host port to 5433
    volumes:
      - pgdata:/home/postgres/pgdata/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
